# Quay.io doesn't allow container image & application repositories in the same organization
# to share a name. In this case, the image is quay.io/coreos/alb-ingress-controller,
# and the Helm chart is quay.io/coreos/alb-ingress-controller-helm. This variable
# overrides the chart name.
nameOverride: alb-ingress-controller

## AWS region in which this ingress controller will operate
## REQUIRED
#
awsRegion: us-east-1

## Resources created by the ALB Ingress controller will be prefixed with this string
## REQUIRED
#
clusterName: eks-workshop

image:
  repository: quay.io/coreos/alb-ingress-controller
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

extraArgs: {}
extraEnv:
  AWS_ACCESS_KEY_ID: "<your_key>"
  AWS_SECRET_ACCESS_KEY: "<your_secret>"

nodeSelector:
  {}
  # node-role.kubernetes.io/node: "true"
  # tier: cs

tolerations:
  {}
  #  - key: "node-role.kubernetes.io/master"
  #    effect: NoSchedule

podAnnotations:
  {}
  # iam.amazonaws.com/role: alb-ingress-controller

podLabels: {}

# How often (in seconds) to check controller readiness
readinessProbeInterval: 10

# How long to wait before timeout (in seconds) when checking controller readiness
readinessProbeTimeout: 1

# How long to wait (in seconds) before checking the readiness probe
readinessProbeInitialDelay : 30

# How long to wait (in seconds) before checking the liveness probe
livenessProbeInitialDelay : 30

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 100Mi

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true

  ## Ignored if rbac.create is true
  serviceAccountName: default

sidecarContainers:
  {}
  ## Additional containers to be added to the alb-ingress-controller pod.
  #  - name: my-sidecar
  #    image: nginx:latest

scope:
  ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
  ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-ingress-class
  #
  ingressClass: alb

  ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
  ## Default: false; watch all namespaces
  #
  singleNamespace: false

  ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
  ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-namespaces
  ## Default: namespace of the ALB ingress controller
  #
  watchNamespace: ""
